from twitter import error  # Errors generated by Twitter API

from datetime import datetime


class MentionsReplies(object):

    def __init__(self, api):
        self.api = api

    def reply_invalid_tweet(self, mention_id, user):
        reply = "@" + user + " Ops @" + user + ", verifique se você tweetou como o exemplo que eu coloquei aqui: " \
                "https://twitter.com/WhoKnowsBot/status/1009919330006589440"

        print(reply)

        # Post the reply on Twitter
        try:
            self.api.PostUpdate(status=reply, in_reply_to_status_id=mention_id)
        except error.TwitterError as e:
            self.add_error_log(e.message, "PostUpdate")

    def reply_mention_how_many(self, mention_id, term, user, users_amount):
        reply = None
        if users_amount == 0:
            reply = "@" + user + " Olá @" + user + " ,infelizmente não encontrei ninguém entre quem você segue " \
                    "falando sobre #" + term + " :("
        elif users_amount == 1:
            reply = "@" + user + " Olá @" + user + ", encontrei " + str(users_amount) + " pessoa que você segue " \
                    "falando sobre #" + term + ". Diga-me, de 1 a 5, o quanto você concorda com esta resposta :)"
        elif users_amount > 1:
            reply = "@" + user + " Olá @" + user + ", encontrei " + str(users_amount) + " pessoas que você segue " \
                    "falando sobre #" + term + ". Diga-me, de 1 a 5, o quanto você concorda com esta resposta :)"

        # Post the reply on Twitter
        try:
            self.api.PostUpdate(status=reply, in_reply_to_status_id=mention_id)
        except error.TwitterError as e:
            self.add_error_log(e.message, "PostUpdate")

    def reply_mention_who_know(self, mention_id, term, user, suitable_user):
        if suitable_user is None:
            reply = "@" + user + " Olá @" + user + ", infelizmente não encontrei ninguém entre seus seguidores que " \
                                                   "sabe sobre #" + term + " :("
        else:
            reply = "@" + user + " Olá @" + user + ", entre seus seguidores quem mais sabe sobre #" + term + \
                    " é @" + str(suitable_user) + ". Diga-me, de 1 a 5, o quanto você concorda com esta resposta :)"

        # Post the reply on Twitter
        try:
            self.api.PostUpdate(status=reply, in_reply_to_status_id=mention_id)
        except error.TwitterError as e:
            self.add_error_log(e.message, "PostUpdate")

    @staticmethod
    def add_error_log(error_message, error_type):
        file = open('files/error_log.txt', 'a')
        file.write(str(datetime.now()) + " - " + error_type + ": " + error_message + "\n")
        file.close()
